"""Minimal type stub for speedtest-cli."""

from typing import Any

class SpeedtestException(Exception): ...
class ConfigRetrievalError(SpeedtestException): ...
class NoMatchedServers(SpeedtestException): ...

class SpeedtestResults:
    def dict(self) -> dict[str, Any]: ...

class Speedtest:
    results: SpeedtestResults
    def get_best_server(self) -> dict[str, Any]: ...
    def download(self) -> float: ...
    def upload(self) -> float: ...
