name: "Crowsnest K8s: CI"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  quality:
    uses: charmarr/.github/.github/workflows/charm-ci.yaml@v2
    with:
      charm-path: charms/charmarr-crowsnest-k8s
      use-parrot: true
    secrets: inherit
