name: "Jellyfin K8s: CI"

on:
  workflow_call:

jobs:
  quality:
    uses: charmarr/.github/.github/workflows/charm-ci.yaml@v2
    with:
      charm-path: charms/jellyfin-k8s
      use-parrot: true
    secrets: inherit

  integration:
    needs: quality
    uses: charmarr/.github/.github/workflows/charm-integration.yaml@v2
    with:
      charm-path: charms/jellyfin-k8s
      use-parrot: false
      substrate: k8s
      substrate-channel: "1.32-classic/stable"
      configure-cni-for-istio: true
    secrets: inherit
